name: CI
on: 
  pull_request:
  push:
    tags:
      - "*"

jobs:
  test:
    name: Lint & test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.x", "20.x", "21.x"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

  typos:
    name: Detect typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run typos
        uses: crate-ci/typos@v1.28.2
